run: 
	java  -cp .:jsoup-1.13.1.jar:postgresql-42.2.18.jar:selenium-server-standalone-3.141.59.jar Main

compile:
	javac -cp  .:jsoup-1.13.1.jar:postgresql-42.2.18.jar:selenium-server-standalone-3.141.59.jar Main.java

clean:
	rm -r Main.class 