run: 
	java  -cp .:jsoup-1.13.1.jar:postgresql-42.2.18.jar:selenium-server-standalone-3.141.59.jar YoutubeScraper

compile:
	javac -cp  .:jsoup-1.13.1.jar:postgresql-42.2.18.jar:selenium-server-standalone-3.141.59.jar YoutubeScraper.java

clean:
	rm -r YoutubeScraper.class 